#!/bin/bash
#SBATCH --account=j1010
#SBATCH --job-name=PyXover
#SBATCH --cpus-per-task=8
#SBATCH --ntasks=1
#SBATCH --share
#SBATCH --mem=8G
#SBATCH --array=1-16%10
#SBATCH --time=99:99:99
#SBATCH --output=slurm-%j.out-%N

IN="loadPyXover"

module load gmt

bash -c "`head -n $SLURM_ARRAY_TASK_ID ${IN} | tail -1`"


