#!/bin/bash
#SBATCH --account=j1010
#SBATCH --job-name=PyAltSim
#SBATCH --cpus-per-task=1
#SBATCH --ntasks=1
#SBATCH --share
#SBATCH --mem=8G
#SBATCH --array=1-373%9999
#SBATCH --time=02:30:00
#SBATCH --output=slurm-%j.out-%N
#SBATCH --exclude=pgda102,pgda103 #,pgda104,pgda105,pgda106,pgda107,pgda108

IN="loadPyAltSim_roughT"

module purge
source /home/sberton2/useful_modules.sh

bash -c "`head -n $SLURM_ARRAY_TASK_ID ${IN} | tail -1`"


