#!/bin/bash
#SBATCH --account=j1010
#SBATCH --job-name=PyXov_0
#SBATCH --cpus-per-task=8
#SBATCH --ntasks=1
#SBATCH --share
#SBATCH --mem=8G
#SBATCH --array=1-21%10
#SBATCH --time=99:99:99
#SBATCH --output=slurm-%j.out-%N
#SBATCH --exclude=pgda102,pgda103,pgda104,pgda105#,pgda106,pgda107,pgda108

IN="loadPyXover"

module purge
source /home/sberton2/useful_modules.sh

bash -c "`head -n $SLURM_ARRAY_TASK_ID ${IN} | tail -1`"


